version: "3.8"

services:
  backend:
    build:
      context: .
      target: backend
      dockerfile: Dockerfile.dev
    image: autonai-backend:latest
    env_file:
      - .env
    ports:
      - 8090:8090
    volumes:
      - .:/app
      - ./output:/output
  frontend:
    build:
      context: .
      target: frontend
      dockerfile: Dockerfile.dev
    image: autonai-frontend:latest
    env_file:
      - .env
    ports:
      - 5173:5173
    volumes:
      - .:/app
    depends_on:
      - backend
